#!/bin/bash

REPO_DIR=$1
MACHINE=$2
DIST=$3
IMAGE=$4
BUILD_DATE=$5

SCRIPT_DIR=$(cd $(dirname $0);pwd)

tmpyml=$(mktemp "/tmp/XXXXXX.yml")
HTTP_STRAGE_URL=http://localhost:8888/build_${MACHINE}_${DIST}_${IMAGE}/${BUILD_DATE}
sed -e "s@DEPLOY_DIR@${HTTP_STRAGE_URL}@g" ${SCRIPT_DIR}/lava/job/${MACHINE}-boot.yml > $tmpyml

/usr/bin/lava-tool submit-job http://buildbot@localhost:10080/RPC2/ $tmpyml

rm -f $tmpyml
