#!/bin/bash

REPO_DIR=$1
MACHINE=$2
DIST=$3
IMAGE=$4

# set env
if [ -e ${REPO_DIR}/poky/oe-init-build-env ]; then
    source ${REPO_DIR}/poky/oe-init-build-env \
               build_${MACHINE}_${DIST}_${IMAGE}
else
    exit 1
fi

echo "DISTRO = \"${DIST}\"" >> ./conf/local.conf
echo "PACKAGE_CLASSES = \"package_deb\"" >> ./conf/local.conf
echo "DL_DIR = \"\${TOPDIR}/../downloads\"" >> ./conf/local.conf
echo "SSTATE_DIR = \"\${TOPDIR}/../sstate-cache\"" >> ./conf/local.conf

exit 0
